<a href="https://colab.research.google.com/github/G0r3s170/sic_ai_2024/blob/main/Tarea_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
'''
Buenos dias, tarde, noches
Nuestro grupo le tocó trbajar con Transposición de Arrays e intercambios de ejes.
Para esto primeros debemos importar la librería y utilizar los métodos "transpose()" o el método abreviado "T"
'''
import numpy as np

Arreglo_base = np.zeros((60), dtype=np.int32).reshape(5,12)
print(Arreglo_base)

Arreglo_base_traspuesto = Arreglo_base.T
print(f"\n {Arreglo_base_traspuesto}")

#utilizando el método transpose(), existe más fuerza para la ejecución.

Arreglo_transpose = np.arange(24).reshape((3,2,4))
print(f"\n {Arreglo_transpose}")

Arreglo_transpose_T1 = Arreglo_transpose.transpose((0,1,2))
#x, y, z

Arreglo_transpose_T2 = Arreglo_transpose.transpose((1,0,2))
#y, x, z

Arreglo_transpose_T3 = Arreglo_transpose.transpose((2,0,1))

print(f"\n {Arreglo_transpose_T1}\n\n {Arreglo_transpose_T2} \n\n {Arreglo_transpose_T3}")

[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

 [[[ 0  1  2  3]
  [ 8  9 10 11]
  [16 17 18 19]]

 [[ 4  5  6  7]
  [12 13 14 15]
  [20 21 22 23]]] 

 [[[ 0  4]
  [ 8 12]
  [16 20]]

 [[ 1  5]
  [ 9 13]
  [17 21]]

 [[ 2  6]
  [10 14]
  [18 22]]

 [[ 3  7]
  [11 15]
  [19 23]]]


In [22]:
'''
Por otro lado para poder utilizar el Swapaxis(), método para cambio de ejes, se aplicaría en matrices de más de 2 dimensiones para cambiar eje x,y,z por eje y,x,z por ejemplo.
Utilizando la misma matriz anterior "Arreglo_transpose" que guardaremos ahora como "Arreglo_axes"
'''

Arreglo_axes = Arreglo_transpose
Arreglo_axes_swaped = Arreglo_axes.swapaxes(0,2)
print(f"Array Base\n {Arreglo_axes}\n\nArray con ejes cambiados con 'swapaxes' \n{Arreglo_axes_swaped}")

Array Base
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

Array con ejes cambiados con 'swapaxes' 
[[[ 0  8 16]
  [ 4 12 20]]

 [[ 1  9 17]
  [ 5 13 21]]

 [[ 2 10 18]
  [ 6 14 22]]

 [[ 3 11 19]
  [ 7 15 23]]]


In [28]:
!git add "Tarea Numpy".ipynb

fatal: not a git repository (or any of the parent directories): .git
